# Generated by Django 3.2.16 on 2023-01-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20230117_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
    ]
